# Generated by Django 3.1 on 2021-06-05 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0002_alter_status_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('0', 'like'), ('1', 'comment')], max_length=20)),
                ('text', models.CharField(blank=True, max_length=300, null=True)),
                ('at_person', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moments.status')),
            ],
        ),
    ]
